region: us-east-1

function_name: start_run_sbg 
handler: service.handler
role: lambda_full_s3
description: import files to SBG and create workflow object to store state of workflow run 

# if access key and secret are left blank, boto will use the credentials
# defined in the [default] section of ~/.aws/credentials.
aws_access_key_id:
aws_secret_access_key:

# dist_directory: dist
timeout: 300 
memory_size: 128 
